import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Button from '@/components/Button'
import Form from '@/components/Form'

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram log in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>

      </header>
      <main className={"${styles.main"}>
        <h1 className={styles.h1}>Instagram</h1>
        <Form/>       
        <Button />
      </main>
      
      
    </>
  )
}
